New version check: error on null/empty
ungoogled-software/ungoogled-chromium pull request #2358
Opened 2023-05-23 14:29 UTC by Ahrotahn

This PR fixes a bug with the new version check action mentioned in #2347 using the fix suggested by @rany2.

2023-05-26 14:19 UTC, networkException approved these changes

2023-05-26 14:23 UTC, rany2 commented
@networkException see my comment above, this doesn't work...

2023-05-26 14:25 UTC, rany2 commented
gah, I didn't submit my comment which is why you didn't see it! it was "pending"

2023-05-27 12:47 UTC, Ahrotahn commented on .github/workflows/new_version_check.yml
>          run: |
From what I can tell from [their documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell) it seems that `-e` is already set by default.

2023-05-27 16:25 UTC, rany2 commented on .github/workflows/new_version_check.yml
>          run: |
That's only for when you pass a single command, if it's multiple lines it doesn't.

2023-05-28 14:09 UTC, networkException approved these changes

2023-05-28 14:53 UTC, rany2 approved these changes

2023-06-06 17:37 UTC, PF4Public requested changes
Please don't merge this PR just yet. I'll explain in a moment.

2023-06-08 20:34 UTC, PF4Public commented
Sorry everyone for stopping this PR. The issue is that with this workflow we sometimes run into secondary limits for some reason, which results in GitHub spamming failed workflow notifications. I remember this was happening even on 2 hour intervals. I kinda got used to them (albeit it is a bit annoying, since I care for failed workflows in _my_ repository). My concern was that if Ahrotahn merges this PR, this could affect where GitHub sends the notifications. But it turned to be a no issue as Ahrotahn kindly browsed the documentation and found out that only changing cron schedule should divert notifications.

Not an issue with this PR per se, but sorry @rany2 if you took it personally.

Now the problem itself could be solved in the action we are using. There is already an issue filled: https://github.com/dblock/create-a-github-issue/issues/39. Solving it probably requires some experience with Node.js and JavaScript (of which I don't have enough). I'd be grateful if someone could solve it :)

2023-06-09 02:56 UTC, rany2 commented
>Not an issue with this PR per se, but sorry @rany2 if you took it personally.

No no, I didn't take anything personally. It's just that you said you'll "explain in a moment" but didn't for a couple of hours. So I assumed you did a review like me but forgot to mark it as complete :)

2023-06-10 22:10 UTC, merged