Improvements in hash checking in downloads.py
ungoogled-software/ungoogled-chromium pull request #3045
Opened 2024-10-01 08:48 UTC by lifesminder

Previous iteration checked whole file and caused memory issues, making programs non-responding. This one improves it, by reading chunks by bytes (default is 8 megabytes).

Tested in Fedora 40.

2024-10-01 13:38 UTC, Ahrotahn commented
This is a good idea considering how large the archives are getting, but there's a couple changes that would need to be made:  
* There is trailing whitespace on the three empty lines you've added.  That is why one of the tests has failed and that would need to be removed.  
* The buffer size should be increased.  The common knowledge of using 4k/8k chunks is somewhat misapplied in situations where the file is always going to be large.  Python added the helper function `file_digest` which isn't available to us with the version we use, but they have chosen a size of 2<sup>18</sup> (262144) which I think we should use instead and will make that take less time to process:  https://github.com/python/cpython/blob/1f4a49ea53516e7ff177beedc09a1e4439b3be1f/Lib/hashlib.py#L195

2024-10-01 15:40 UTC, lifesminder commented
> This is a good idea considering how large the archives are getting, but there's a couple changes that would need to be made:
> 
> * There is trailing whitespace on the three empty lines you've added.  That is why one of the tests has failed and that would need to be removed.
> * The buffer size should be increased.  The common knowledge of using 4k/8k chunks is somewhat misapplied in situations where the file is always going to be large.  Python added the helper function `file_digest` which isn't available to us with the version we use, but they have chosen a size of 218 (262144) which I think we should use instead and will make that take less time to process:  https://github.com/python/cpython/blob/1f4a49ea53516e7ff177beedc09a1e4439b3be1f/Lib/hashlib.py#L195

cool, for these purposes I have added an extra `chunk_bytes` argument, in order to make it scalable and set required size in specific scenarios.

about whitespace I can't say much, as I don't have an experience on python 2.x versions programming :)

2024-10-02 09:07 UTC, lifesminder reviewed
minor fixes

2024-10-02 12:07 UTC, rany2 requested changes

2024-10-02 12:07 UTC, rany2 commented on utils/downloads.py
>  def unpack_downloads(download_info, cache_dir, output_dir, skip_unused, sysroot, extractors=None):
Should fix code_check CI issue:

```suggestion

def unpack_downloads(download_info, cache_dir, output_dir, skip_unused, sysroot, extractors=None):
```

2024-10-02 13:15 UTC, Ahrotahn commented
There's a different problem this time:  There needs to be two line breaks before `unpack_downloads`.  @rany2's suggestion should fix that.  

The problem you had previously wasn't with the empty lines, it was that those lines *weren't* empty.  They contained space characters.  

Since your commits are signed by Github it seems you're using their editor, and unfortunately that doesn't have the option to show whitespace characters.  If you happen to use a userscript extension there is a script that can be used to add that functionality:  https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-code-show-whitespace

2024-10-03 07:13 UTC, lifesminder commented
> Minor thing: you keep saying the default is 8 megabytes in the code and PR, but it's actually 8192 bytes (8 KiB). Anyway as stated in [#3045 (comment)](https://github.com/ungoogled-software/ungoogled-chromium/pull/3045#issuecomment-2385931844), the default is too low and should be increased.

oh okay, which size should it be?

2024-10-03 09:37 UTC, rany2 requested changes

2024-10-03 09:37 UTC, rany2 commented on utils/downloads.py
> +def check_downloads(download_info, cache_dir, chunk_bytes=8192):
```suggestion
def check_downloads(download_info, cache_dir, chunk_bytes=262144):
```

2024-10-03 09:39 UTC, rany2 requested changes

2024-10-03 09:39 UTC, rany2 commented on utils/downloads.py
> +                # Read file in chunks. Default is 8 megabytes
```suggestion
                # Read file in chunks. Default is 262144 bytes.
```

2024-10-05 19:48 UTC, lifesminder commented
hi, is code reviewed yet?

2024-10-05 20:26 UTC, rany2 commented
You marked my suggestions as resolved without making any changes

2024-10-06 15:18 UTC, lifesminder commented
> You marked my suggestions as resolved without making any changes

so how to put them into commit? It's my first time to make a pull request, sorry for too much questions :3

2024-10-07 13:00 UTC, Ahrotahn commented
There should be a button to add the suggestion as a commit.  There has also been a change we recently merged that causes a conflict with these changes, so you would also need to use the resolve conflicts button to handle that.  

Alternatively I could take some time later to rebase the changes and add those suggestions for you so long as your branch allows us to push to it.

2024-10-10 16:31 UTC, PF4Public commented
I think we'll have to squash commits before merging to tidy it up a bit.

2024-10-10 23:14 UTC, Ahrotahn commented on utils/downloads.py
>          download_path = cache_dir / download_properties.download_filename
One last set of spaces:  
```suggestion
        get_logger().info('Verifying hashes for "%s" ...', download_name)

        download_path = cache_dir / download_properties.download_filename
```

2024-10-10 23:34 UTC, Ahrotahn commented
@PF4Public The 'squash and merge' option should handle that for us

2024-10-11 15:39 UTC, PF4Public commented
> @PF4Public The 'squash and merge' option should handle that for us

yep, I meant just that

2024-10-14 13:18 UTC, Ahrotahn approved these changes
Thanks @lifesminder!

2024-10-14 15:36 UTC, networkException approved these changes

2024-10-14 16:39 UTC, PF4Public approved these changes
I trust you guys with python :)

2024-10-14 17:51 UTC, merged

2024-10-16 15:57 UTC, lifesminder commented
> Thanks @lifesminder!

no problem :Ճ